### ISSUE TITLE
One day missing b/w start_date and end_date for 025deg_jra55_iaf_omip2_cycle6

### ISSUE THREAD

**Issue by utkarshgupta95** [ACCESS-NRI/access-nri-intake-catalog#114]
In the experiment 025deg_jra55_iaf_omip2_cycle6 for the conda env:analysis3, there is a day missing between start_date and end_date with freq 1day for some variables. For example the start_date for a record is 1957-12-31 00:00:00 and end_date is 1958-12-30 00:00:00, then the next start_date is 1958-12-31 00:00:00 instead of 1958-12-30 00:00:00

total_ocean_evap_heat : total latent heat flux into ocean (<0 cools ocean)

rhoave : global mean ocean in-situ density from ocean_density_mod

total_ocean_fprec_melt_heat : total heat flux to melt frozen precip (<0 cools ocean)

total_ocean_hflux_evap : total ocean heat flux from evap transferring water across surface

total_ocean_mh_flux :

total_ocean_runoff_heat : total ocean heat flux from liquid river runoff

eta_global : global ave eta_t plus patm_t/(g*rho0)

total_ocean_runoff : total liquid river runoff (>0 water enters ocean)

total_net_sfc_heating : total ocean surface flux from coupler and mass transfer

temp_surface_ave : Global mass weighted mean surface temp in liquid seawater

total_ocean_swflx : total shortwave flux into ocean (>0 heats ocean)

total_ocean_heat : Total heat in the liquid ocean referenced to 0degC

total_ocean_lprec : total liquid precip into ocean (>0 enters ocean)

salt_surface_ave : Global mass weighted mean surface salt in liquid seawater

total_ocean_sfc_salt_flux_coupler : total_ocean_sfc_salt_flux_coupler

total_ocean_lw_heat : total longwave flux into ocean (<0 cools ocean)

salt_global_ave : Global mean salt in liquid seawater

total_ocean_evap : total evaporative ocean mass flux (>0 enters ocean)

total_ocean_fprec : total snow falling onto ocean (>0 enters ocean)

total_ocean_salt : total mass of salt in liquid seawater

total_ocean_hflux_prec : total ocean heat flux from precip transferring water across surface

total_ocean_pme_river : total ocean precip-evap+river via sbc (liquid, frozen, evaporation)

pe_tot : Globally integrated ocean potential energy

total_ocean_melt : total liquid water melted from sea ice (>0 enters ocean)

total_ocean_hflux_coupler : total surface heat flux passed through coupler

total_ocean_sens_heat : total sensible heat into ocean (<0 cools ocean)

total_ocean_river : total liquid river water and calving ice entering ocean

total_ocean_swflx_vis : total visible shortwave into ocean (>0 heats ocean)

ke_tot : Globally integrated ocean kinetic energy

total_ocean_river_heat : total heat flux into ocean from liquid+solid runoff (<0 cools ocean)

temp_global_ave : Global mean temp in liquid seawater

**Comment by dougiesquire** [comment]
Thanks @utkarshgupta95. As in #113, this is the result of missing metadata in the files themselves. In the case of these files, there are multiple time instances per file, but there is no time bounds information available. In this case (as in the cosima-cookbook), [the start_ and end_dates are just taken to be the first and last times in the file](https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/f7ca77919448ef5beb56c3b6d7ae29a19a649e12/src/access_nri_intake/source/utils.py#L49). Again, I'm not really sure what can be done here as I don't think we want to get in the habit of band-aiding issues that really should be fixed in the files themselves. Sorry, that's not very helpful, I know. I'm curious if @aidanheerdegen has opinions about what should be done?

**Comment by aidanheerdegen** [comment]
See comment in the related issue https://github.com/ACCESS-NRI/access-nri-intake-catalog/issues/113#issuecomment-1721097511
