### ISSUE TITLE
[BUG] build_all scripts can't download schema

### ISSUE THREAD

**Issue by anton-seaice** [ACCESS-NRI/access-nri-intake-catalog#137]
# Describe the bug

When a user submits the `bin/build_all.sh` to the PBS queue, the build fails if the user doesn't have a cached copy of the assets json schema from https://github.com/ACCESS-NRI/schema (i.e. if the schema version has changed since last run)

# To Reproduce

Delete ~/.cache/pooch/

Run `qsub -v version=test bin/build_all.sh`

# Additional context

Workaround is to start a python session on a login node, and run 

`from access_nri_intake import source, catalog` to cache a copy of the schema

**Comment by dougiesquire** [comment]
Thanks @anton-seaice. I know you know, but for others watching this is because the work nodes on Gadi do not have network access and so cannot download the schema if it is not cached. We'll be able to ensure this is avoided once we have the catalog build in the CD (#133), but for now a PR adding a note about this to the docs would be very welcome.
