### ISSUE TITLE
Return type for parse_access_ncfile

### ISSUE THREAD

**Issue by marc-white** [ACCESS-NRI/access-nri-intake-catalog#186]
# Is your feature request related to a problem? Please describe.

The return out of `BaseBuilder.parse_access_ncfile` is currently a long tuple of assorted file information. This makes it difficult to remember which item is which during debugging & testing.

# Describe the feature you'd like

We should consider if `parse_access_ncfile` should return a `dict` instead. This will have the advantage of making the return more human-legible. (It will also simplify the `parser` functions of the various builders, which effectively all rebuild the tuple return into a `dict` anyway.)

# Describe alternatives you've considered

Nil.

# Additional context

I'm about to add another issue (#187) to suggest an expansion of the testing for builders, which will be made easier by this feature.

**Comment by charles-turner-1** [comment]
The changes in #212 should cover this - I'd initially thought that we'd want to have separate flags in the catalogue for data and coordinate variables, so I factored it out as a way of keeping track of changes. It turned out to be unnecessary to do that, but I agree the long tuple is difficult to keep track of & creates a lot of unnecessary context.

I used a dataclass, not a dict, however - let me move a lot of the repetitive stuff inside the class. Given pydantic is used pretty heavily upstream in intake-esm, I wonder whether we might want to use a pydantic dataclass? It might be handy to enforce the extra validation?
