### ISSUE TITLE
Default to a "latest" version?

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/access-nri-intake-catalog#191]
The ACCESS-NRI Intake catalog is versioned in the same way as the `access-nri-intake` package (see `/g/data/xp65/public/apps/access-nri-intake-catalog`).

The default version is equal to the version of `access-nri-intake` being used, though the version can be specified when the catalog is loaded, e.g.

```python
import intake

cat = intake.cat.access_nri
cat.metadata["version"]

cat_another_version = intake.cat.access_nri(version="v0.1.0")
cat_another_version.metadata["version"]
```

This default behaviour ensures that the catalog version and the version of `access-nri-intake` being used are compatible. However, it also means that users with old versions of `access-nri-intake` installed won't use the most recent version of the catalog by default.

We should consider instead defaulting to a "latest" version of the catalog that symlinks to the most recent released version. To manage compatibility issues, we could have "latest" versions for each major release (e.g. `latest_v1`) and ensure we increment the major version when changes are introduced to `access-nri-intake` that break compatibility with old catalogs.

**Comment by marc-white** [comment]
This sounds like an eminently sensible idea. I can think of a few ways to do this in practice:
1. We could store a catalog version (separate to the `access-nri-intake-catalog` version) within the package. The package would then load the newest catalog with that catalog version by default (and catalogs would be created with the current catalog version). It could also auto-reject any attempt to load a catalog with an incompatible version number.
2. We set up a convention where we only increment the major version number of `access-nri-intake-catalog` when we make a change that will invalidate previous catalogs, and select which catalogs to open based on that.
3. The catalog itself could store which version of `access-nri-intake-catalog` it is known to be compatible with/was generated with. We could then have each version of `access-nri-intake-catalog` know which back-versions of itself that generate compatible catalogs.

There are a few questions around any implementation:

- How many catalog versions currently exist? (Gadi is down, else I would just check for myself.) And of those, are there any that are currently incompatible with the up-to-date `access-nri-intake-catalog`?
- What is the purpose of opening an out-of-date catalog? Will we ever hit the point where there's something removed from the catalog that people will want to have access to (and if that's the case, why would we pull it from the catalog)?

**Comment by dougiesquire** [comment]
> We could store a catalog version (separate to the access-nri-intake-catalog version) within the package.

The default catalog version is defined [here](https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/e67d2ba9613ae0e0b13660b04b57e50333aec149/src/access_nri_intake/data/catalog.yaml#L20). As you can see it is set to the `access-nri-intake` version. This is done when the [catalog is built](https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/e67d2ba9613ae0e0b13660b04b57e50333aec149/src/access_nri_intake/cli.py#L210-L212).

As above, I propose changing the default catalog version to "latest", and have a version `latest` in `/g/data/xp65/public/apps/access-nri-intake-catalog` that is a symlink to the latest catalog version. This would mean that a user always gets the latest version of the catalog by default (regardless of the version of `access-nri-intake` they are using) but they could also open a specific version if they wanted to.

To answer your questions:

> How many catalog versions currently exist? (Gadi is down, else I would just check for myself.) And of those, are there any that are currently incompatible with the up-to-date access-nri-intake-catalog?

```bash
$ ls -alh /g/data/xp65/public/apps/access-nri-intake-catalog
total 36K
drwxrwsr-x+ 9 ds0092 xp65_w 4.0K May  7 08:56 .
drwxr-sr-x  8 rb5533 xp65   4.0K Aug 28 15:07 ..
drwxrwsr-x+ 3 ds0092 xp65_w 4.0K Sep 29  2023 v0.0.10
drwxrwsr-x+ 3 ds0092 xp65_w 4.0K Jul 10  2023 v0.0.8
drwxrwsr-x+ 3 ds0092 xp65_w 4.0K Jul 20  2023 v0.0.9
drwxrwsr-x+ 3 ds0092 xp65_w 4.0K Nov 29  2023 v0.1.0
drwxrwsr-x+ 3 ds0092 xp65_w 4.0K Mar  4  2024 v0.1.1
drwxrwsr-x+ 3 ds0092 xp65_w 4.0K Mar 28 14:12 v0.1.2
drwxrwsr-x+ 3 ds0092 xp65_w 4.0K Aug 29 16:54 v0.1.3
```
but we could probably ditch the `v0.0` ones as they were really test releases. I _think_ all catalog versions should be compatible with the latest `access-nri-intake`

> What is the purpose of opening an out-of-date catalog? Will we ever hit the point where there's something removed from the catalog that people will want to have access to (and if that's the case, why would we pull it from the catalog)?

Reproducibility is one reason. It means users can be confident they are opening the same data (even if new data has since been added to the catalog). Also, if there's an issue with the latest catalog version it's convenient to be able to quickly switch to an earlier, working version.

**Comment by marc-white** [comment]
> > We could store a catalog version (separate to the access-nri-intake-catalog version) within the package.
> 
> The default catalog version is defined [here](https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/e67d2ba9613ae0e0b13660b04b57e50333aec149/src/access_nri_intake/data/catalog.yaml#L20). As you can see it is set to the `access-nri-intake` version. This is done when the [catalog is built](https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/e67d2ba9613ae0e0b13660b04b57e50333aec149/src/access_nri_intake/cli.py#L210-L212).
> 
See, this is why I shouldn't blast through suggestions quickly when I'm tired...

Do you envisage updating the code so it can intelligently work out if the symlink to 'latest' needs to be updated when a new catalog version is generated, or do you expect that to be a manual step that someone needs to jump into the filesystem to do?

**Comment by dougiesquire** [comment]
> Do you envisage updating the code so it can intelligently work out if the symlink to 'latest' needs to be updated when a new catalog version is generated, or do you expect that to be a manual step that someone needs to jump into the filesystem to do?

We could just remove the old symlink and create the new one as the final step in the build process?

**Comment by marc-white** [comment]
> > Do you envisage updating the code so it can intelligently work out if the symlink to 'latest' needs to be updated when a new catalog version is generated, or do you expect that to be a manual step that someone needs to jump into the filesystem to do?
> 
> We could just remove the old symlink and create the new one as the final step in the build process?

That's viable, although you'd need to be certain you were always creating a new catalog version, and not repairing an older catalog (or providing an small update to an existing catalog that's behind the 'latest' for whatever reason).

**Comment by marc-white** [comment]
OK, so what I think needs to be done here is:

- [ ] Alter `data/catalog.yaml` to point to version `latest-N` by default, where `N` is the major version number of `access-nri-intake-catalog`
- [ ] Disable the 'write-back' feature of the catalog build that returns the new version number into `data/catalog.yaml`
- [ ] Add functionality to list the available catalog versions, including starring the current default, and showing the linkage between 'named' and 'numbered' versions
- [ ] Add something to catalog build to automagically determine if the latest symlink for the current major version needs updating

I'm still pondering how (or even if) it's possible to define backwards and forwards compatibility between `access-nri-intake-catalog` and catalogues.

**Comment by marc-white** [comment]
**CATALOG VERSIONING**

The more I think about it, the more I'd like to have the catalog version numbers be completely distinct/distinguishable from the `access-nri-intake-catalog` version numbers. I think there's too much scope for confusion if we use the X.Y.Z pattern for both.

Therefore, I'd propose to change the catalog version numbers to one of the following options:

1. _Sequential whole numbering_: Every new catalog would simply be an integer, i.e. the 10th catalog we build would be catalog `10`. This is the simplest option, although it makes life slightly harder to do some of the automagic version detection I had in mind (see above).
2. _Date-based versioning_: We make the catalog version be a timestamp, e.g., `2024-10-24`. I can't imagine that we'd be making more than one public catalog build per day, and it's easier to do instrinsic ordering, e.g. `ls -lr` will correctly order the catalogs, newest to oldest.

The human in me prefers option 1; the programmer prefers option 2. Thoughts @dougiesquire @charles-turner-1 @rbeucher ?

**Comment by charles-turner-1** [comment]
I think I'd be in favour of date based versioning. `catalog v10` is definitely easier to remember than `catalog v2024-10-24` - but I'm not sure that would remain the case when it becomes `catalog v73` versus `catalog v2025-03-12`.

**Comment by rbeucher** [comment]
I vote for the option 2

**Comment by marc-white** [comment]
**THE `catalog.yaml` FILE**

The file [`data/catalog.yaml`](../blob/main/src/access_nri_intake/data/catalog.yaml) is the metadata that `access-nri-intake-catalog` links into `intake` to let you do this:
```python
import intake
cat = intake.cat.access_nri
```

The provenance of this file is a bit unusual. The way a new catalog gets built is:

- The catalog build process is triggered, using some new version (not yet released) of the `access-nri-intake-catalog` code base.
- As the last step of the build process, if the `--no-update` flag isn't set, the `data/catalog.yaml` in the code base used gets overwritten with information from this new catalog build.
- The developer is then meant to commit this changed `data/catalog.yaml` back into the repository and trigger the release process (IAW [the current instructions](https://access-nri-intake-catalog.readthedocs.io/en/latest/management/release.html) for preparing a release).

The (in)ability to overwrite `data/catalog.yaml` is what's tripping @rbeucher  up in #215 .

In theory, a lot of important information is written back into `data/catalog.yaml` during this process, including the catalog `columns_with_iterables`, the data locations, catalog version, etc. However, in practice, a lot of these values are held constant by the shell variables defined in [build_all.sh](../blob/main/bin/build_all.sh). All that will realistically change between catalog versions is:
- The `storage` flags, telling the system which projects are required to access the full catalogue;
- The catalog default version (which, under this issue, we probably want to hold constant to a symlinked `latest` or `latestN` version).

Other things, like the `path` to the catalog, may change once or twice if, e.g., `xp65` disappears, but those occurrences are likely to be so far apart that a manual update is the easiest thing to do there.

Therefore, there are a few things we can do instead of letting the build process write back to `data/catalog.yaml`:

1. We still generate the dictionary that would get written back to `data/catalog.yaml`, but instead of writing it back to the code base, we simply `diff` it (or equivalent) against what's in the code base, and give warning(s) back to the developer, telling them what needs to be changed in the code;
2. We move `data/catalog.yaml` into the `xp65` file system instead of the repository (and potentially, have a different `catalog.yaml` for each major version of `access-nri-intake-catalog`, given a change of catalog structure will probably entail a new major code version). This will mean that, if whatever job installs `access-nri-intake-catalog` doesn't have `xp65` access, it will fail ([read more here](https://access-nri-intake-catalog.readthedocs.io/en/latest/management/overview.html)).

Option 1 (the diff) is probably the safest. In practice, changes to `data/catalog.yaml` should be minimal, but should be made explicitly visible to the developer for sanity checking. I'm also concerned about not creating additional gremlins at install time, given it frequently won't be one of the code developers doing that.

However, Option 2 provides a better, more ideologically pure separation between code that does things, and metadata that describes the stuff on disk that the code operates on. This means, e.g., if we add more experiments that require us to expand the `storage` flags, we can make that update without doing a whole new `access-nri-intake-catalog` release. However, that could possibly create installation issues, and it make break `intake` for a user who has `access-nri-intake-catalog` installed in their environment, but hasn't turned on `xp65` access (we may need to test that).

Thoughts @charles-turner-1 @dougiesquire @rbeucher ?

**Comment by rbeucher** [comment]
I’m leaning toward option 2, even if it might break for anyone without xp65 access. The catalog’s mainly meant for xp65, but it’d be great if the code were more portable. One way to handle this could be to add a config file in the user’s home directory, or we could build in some Gadi-specific behavior.

Also, just a reminder—we’re the ones building these catalogs. Users can create their own if needed, but they shouldn’t be able to write to xp65, so we can keep things secure and consistent.

**Comment by marc-white** [comment]
@rbeucher we may be able to work on portability - for example, for this ticket I've already added a warning if the `data/__init__.py` can't attach the live catalog to `intake.cat.access_nri` (previously it would error out and stop the package import).

**Comment by charles-turner-1** [comment]
Yup, I also think option 2 seems cleaner. I really like the idea of the warning on the attribute lookup too - perhaps that would be a good place to add some handling of user supplied configs? That way the user is unlikely to accidentally overload the full catalog with their own one by accident.

**Comment by marc-white** [comment]
I added the `RuntimeWarning` to the catalog attachment (i.e., the setting of the variable `data` in `data/__init__.py`) for two different reasons:

1. I've added a `utils.py` to the `data` submodule to get started on some of the catalog versioning. When trying to import this, the attempt to set `data` within the submodule `__init__.py` is triggered, which previously failed out if the catalog couldn't be accessed;
2. When `access-nri-intake-catalog` gets installed, the catalog location gets hooked into `intake` via the `pyproject.toml`'s `[project.entry-points."intake.catalogs"]` entry (see the Intake documentation [here](https://intake.readthedocs.io/en/latest/data-packages.html)). As per the docs, this is stored as a reference only, rather than hitting every possible data package at load time. Therefore, when you try to do `cat = intake.cat.access_nri`, it really is trying to grab `access_nri_intake_catalog.data.data`. Rather than error out, I now provide a `RuntimeWarning`, and return an empty `Intake.catalog.Catalog` object instead.

@charles-turner-1 I'm not sure what you mean when you say user supplied configs - do you mean the possibility of a user attaching more things to the existing catalog?

**Comment by charles-turner-1** [comment]
My bad, I was a bit vague- I was following up on @rbeucher's comment about config files in a users home directory - potentially by only checking for such a configuration & handling the behaviour specified by a config if intake fails to access `access_nri_intake_catalog.data.data`, we could let users specify fallback behaviour without having to worry about changing any default behaviour if they have access to xp65?

So in addition to the spitting out a runtime warning, we could add some additional logic related to checking for a user supplied config - and then return a non empty catalog if the user has provided a configuration specifying to grab another one somehow?

Caveat: I could well be barking completely up the wrong tree here - it just strikes me that shoving the user config read into the exception handling will ensure a user won't be able to topple the default catalog by accident.

**Comment by marc-white** [comment]
@rbeucher what exactly would we be looking for in these user-specific config files? E.g., a location for their own version of the catalog?

**Comment by rbeucher** [comment]
Yes, @charles-turner-1, that’s along the lines of what I was thinking. The code is currently tied to xp65, but instead of hardcoding catalog paths or Gadi-specific variables, we could set those to be read from a config file in the user’s home directory. This would let users easily adjust code behavior as needed.

We could also include a default config file with paths pointing to xp65.

Environment variables are also an option...I would prefer a config file though...

**Comment by marc-white** [comment]
@rbeucher happy with a config file, we can add this as part of this upgrade.

**Comment by charles-turner-1** [comment]
> 
> Environment variables are also an option...I would prefer a config file though...
>

Strongly agree with this - took me far longer than it should have to understand environment variables & I suspect I'm not the only one. A config file is much more approachable.

**Comment by marc-white** [comment]
OK, so we can define a location in the user's home area, say, `~/.access_nri_intake_catalog`, that can hold a configuration file. Then, there's a few questions to mull over:

1. What form does this configuration file take? Is it simply a customized version of `data/catalog.yaml` that defines the `Intake-ESM` datastore that gets attached to `intake.cat.access_nri`, or is it some other pointer?
2. What's the correct hierarchy? Normally, you'd let a user's config file override the default, but in this case, I'm tempted to do it the other way around; mandate that users use the 'official' `xp65` catalog, unless they don't have access to that, at which point they can do something custom.
3. What should the default behaviour be if a config/catalog definition not be found? Should there be an onboard package default as the last resort, or do we simply error out at the point?

**Comment by rbeucher** [comment]
1. We could have a customized version of the `catalog.yaml` or pointers to the different catalog versions (with one catalog.yaml file for each catalog) We just need to be able to handle multiple versions.
2. We can ship a default config file with the package that users can modify if they want to.
3. I think we should return a "catalog not found" exception.

@charles-turner-1 any thoughts on this?

**Comment by charles-turner-1** [comment]
Perhaps we could:
1. Ship a default config file with the package, and add a console script (say `$ access-nri-catalog-configure` that copies the default config to `~/.access_nri_intake_catalog/config` or something along those lines. 
    - We could additionally add a flag that drops the user into a CLI where they can pick options in the process - I'm thinking something similar to what `npm create vite@latest` will give you. 
2. Set the package to use the config in `~/.access_nri_intake_catalog/config` if it exists, and fall back to the one contained within the package. This is (IIRC) the default behaviour of how a lot of linux configurations work, so should be relatively(?) intuitive. 
    - I think we should spit out a warning if we are using a user defined configuration - just so the user knows that they are using a non default configuration.
    - I think this is probably going to be easier to reason about than my earlier suggestion of only looking for a user config in the exception handling if the catalog doesn't load - it won't require the user to break the catalog to use a custom config.
    - Given people might want to turn this config on and off, maybe we also want to add a flag to it then enables/disables its use? This would save people constantly doing stuff like `$ mv .config .config_disabled` and back. This could look something like, eg.
```yaml 
ENABLED: false # Toggles whether access-nri-intake-catalog will use this configuration or ignore it completely
catalog_version: 0.1.14
...
```
3.  I think on balance it probably does make sense to return a catalog not found exception. If we don't have a catalog, then the users workflow is almost certainly broken anyway - we might as well fail early.

**Comment by charles-turner-1** [comment]
Created an issue for a config tool in #235. I'm going to just build a skeleton for the TUI and then we can couple it to the config file.

**Comment by marc-white** [comment]
After doing some reading, I have an idea for handling the `catalog.yaml` file that I'm going to start implementing. It goes like this:

- The default `catalog.yaml` file will live on `xp65` with the data. However, there will be two 'fall-back' versions:
  - The user may place a `catalog.yaml` in their home area to supersede the one on `xp65`. The main reason I can think they might want to do this is if they want to use a superseded version of `catalog.yaml` (see the update process below).
  - As a final fall-back, a version will be held in the code repository. This is mostly to provide a template.
- The catalog build process will write back changes to `catalog.yaml`. However, instead of just blowing away the previous version, it will now do the following:
  - `catalog.yaml` will now specify a min and max value for the catalog version number. I've tested it against our new pattern, and confirmed that < and > work as expected for the new format.
  - If no `catalog.yaml` exists, the build process will write a new one. It will set the `min` catalog value to the lowest catalog version currently on `xp65`, and the `max` to the current catalog version.
  - If a `catalog.yaml` exists, the build process will compare the possible new YAML against the old YAML. 
    - If there are no changes of substance between the old and the new, all it will do is update the old YAML with a new `max` version number (and possibly update the `storage_flags` metadata).
    - If there are changes of substance, it will move the old `catalog.yaml` to a new file (name TBD, but for the sake of this, let's say `catalog-<min version>-<max version>.yaml`), and put the new version in as `catalog.yaml`. Then, by default, doing `intake.cat.access_nri` will give you the new catalog version; if you want the old catalog, you can grab `catalog-<min version>-<max version>.yaml` and put it in your home area.

**Comment by charles-turner-1** [comment]
Sounds good to me. Do you want to hijack the cli changes in #237 to copy a template catalog to the users home area?

**Comment by marc-white** [comment]
> Sounds good to me. Do you want to hijack the cli changes in #237 to copy a template catalog to the users home area?

Probably. I was just considering if we should provide command-line tools to pull these things in, rather than getting users to do manual copying.

**Comment by charles-turner-1** [comment]
FYI: I think it might be possible to describe a user defined catalog in the same `catalog.yaml` file that the provided the standard access_nri_catalog - Dougie pointed me towards some of the talks Martin Durant gave on intake last week which I've been slowly digesting.

This would allow something like (NB. the below code block doesn't work but seems to be in the ballpark - still figuring it out): 

```python
>>> import intake
>>> intake.cat.access_nri
<access_nri catalog with 94 source(s) across 2272 rows>
>>> intake.cat.userdef
<access_nri catalog with 2 sources across 849 rows>
```

I'm leaving this comment here instead of @marc-white's PR (#243) as I think it's a semi-separate issue & I'll open a new issue once I've satisfied myself that I understand whether it is possible and how we might do it.
