### ISSUE TITLE
Exclude (or flag) coordinates

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-nri-intake-catalog#63]
It would be good to make it possible to only show diagnostic variables in the catalogue, by excluding all coordinates.

This could be achieved by not including coordinate variables in the catalogue at all: they are accessible when variables are loaded that contain those coordinates.

Another option would be to include a column that with a flag that indicates if the variable is a coordinate, or not. In that way they could be filtered out by the user (I assume).

**Comment by dougiesquire** [comment]
Thanks for reporting @aidanheerdegen. At the moment, only 1D coordinates are excluded since files are opened with `decode_cf=False` and `decode_coords=False`. This is why `TLON` etc are still in the Intake-ESM datastores.

We can obviously easily switch these flags to `True`, which in the case of your example file would then also exclude `TLON`, `TLAT`, `ULON`, `ULAT` and `NCAT`. This will add some overhead, but may need to be done anyway for [extracting grid information](https://github.com/ACCESS-NRI/access-nri-intake-catalog/issues/112).

Thinking more about this, I'm not sure we want to *exclude* coordinates, since I think it is useful to be able to search on these. In ACCESS-OM2 output, for example, grid information is included in a separate `ocean_grid.nc` file that users might want to search for based on coordinate names. So flagging may be a better approach after all.

> and others that aren't classified as coordinates but we would also want to exclude.

I don't think I understand how you're suggesting we flag these in a robust way. In fact, it's not even clear to me what's in this list. I think you're referring to properties of the grid (e.g. `dxt`, dyt` etc)? Does this also include areas? Is it things that aren't dependent on time?

**Comment by dougiesquire** [comment]
> So flagging may be a better approach after all.

It just occurred to me that _flagging_ coordinates is going to be difficult with the way Intake-ESM is currently set up to handle multi-variable assets (files). Multi-variable assets are included as a single row in an Intake-ESM datastore, with a column containing a list of the variables available in that file - see [here](https://intake-esm.readthedocs.io/en/stable/how-to/use-catalogs-with-assets-containing-multiple-variables.html). There's thus no easy way include per-variable attributes in the table.

**Comment by aidanheerdegen** [comment]
Ok, thanks for the informative response @dougiesquire. 

I agree, I think I was being a bit ... cavalier ... with my wish to filter out a large number of variables as "griddy". There are indeed good use cases for many of these. 

For my use case I think we'll do what the COSIMA Explorer does, use some heuristics to "hide" variables that are potentially of little use to expose at a high level, but allow for them to be shown if a user wishes.

Regarding [extracting grid information](https://github.com/ACCESS-NRI/access-nri-intake-catalog/issues/112) that actually has the potential to be a useful way to exclude variables: if they exist in a higher-quality grid file, then use that and "hide" the same variables that are present in the data file. I am thinking specifically of un-masked grid coordinates. That may require more contemplation, so I'll just leave that thought bubble there and back away slowly ...
