### ISSUE TITLE
Filename extension issues in cat.search()

### ISSUE THREAD

**Issue by headmetal** [ACCESS-NRI/access-nri-intake-catalog#74]
I'm not sure if this is an intended behaviour or a bug (and I apologise in advance if this is in fact intended):

In the following case, if I attempt to explicitly nominate a given filename `ocean_month.1mon` from the available `keys()` it returns an empty `data_dict`:

<img width="724" alt="image" src="https://github.com/ACCESS-NRI/access-nri-intake-catalog/assets/5642928/0697d790-0f7b-46ec-b4eb-41a6d1938f2c">

However, if I add a wildcard and exclude `.1mon` from the filename, the `data_dict` is populated as expected:

<img width="724" alt="image" src="https://github.com/ACCESS-NRI/access-nri-intake-catalog/assets/5642928/1663b369-b8cf-4d57-96f8-b5bb995d022e">

I'm guessing the `.1mon` isn't the _real_ file extension, but is in fact part of the filename - so is messing up loading the file?

**Comment by dougiesquire** [comment]
Thanks @headmetal . `ocean_month.1mon` is not a filename, it's a "key" for a dataset in the intake-esm datastore. The keys are intake-esm's way of knowing how to concatenate all the files in the datastore into "datasets". For ACCESS-OM2 datastores, the keys are made up of two fields from the table (see `subcat.df` to see the table):

- the `file_id`, which is parsed from the filename (the `ocean_month` part in your case)
- the `frequency` (the `1mon` part)

It you want to load a dataset directly by key, you can use something like:

```python
subcat["ocean_month.1mon"].to_dataset_dict()
```

Alternatively, in this specific case where the filename `ocean_month` alone defines a unique dataset, you could get the same data by querying on the `filename` field as you have done above, e.g.:

```python
subcat.search(filename="ocean_month").to_dataset_dict()
```

However, it isn't always guaranteed that filename alone defines a unique dataset. E.g. I've come across model runs containing two files with the same name containing data at different frequencies. That's why the `frequency` info is also needed in the key.

I hope this helps and doesn't make things even less clear. Some more info on keys in intake-esm can be found here: https://intake-esm.readthedocs.io/en/stable/how-to/understand-keys-and-how-to-change-them.html

**Comment by dougiesquire** [comment]
This issue originated from a confusing line in `example_usage.ipynb`. I've added a note for how to improve this in https://github.com/ACCESS-NRI/access-nri-intake-catalog/issues/75#issuecomment-1553897362, so I'm closing this issue
